local builtin = require("telescope.builtin")
vim.keymap.set("n", "<leader>E", "<cmd>Explore<CR>", { silent = true, noremap = true })
vim.keymap.set("n", "<leader>ff", "<cmd>Telescope find_files<CR>", { silent = true, noremap = true })
vim.keymap.set("n", "<leader>pf", builtin.find_files, {})
vim.keymap.set("n", "<leader>ps", function() builtin.grep_string({ search = vim.fn.input("Grep > ")}); end)
vim.keymap.set("n", "<C-p>", builtin.git_files, {})
vim.keymap.set("n", "<leader>ww", "<cmd>write<CR>", { silent = true, noremap = true })
vim.keymap.set("n", "<leader>PP", "<cmd>Prettier<CR>", { silent = true, noremap = true })
