return {
	-- "akinsho/bufferline.nvim",
	-- dependencies = { "nvim-tree/nvim-web-devicons" },
	-- version = "*",
	-- opts = {
	-- 	options = {
	-- 		mode = "tabs",
	-- 		separator_style = "slant",
	-- 		offsets = {
	--
	-- 			{
	-- 				filetype = "neo-tree",
	-- 				text = "Neo-tree",
	-- 				highlight = "Directory",
	-- 				text_align = "left",
	-- 			},
	-- 		},
	-- 	},
	-- },
	-- config = function(_, opts)
	-- 	require("bufferline").setup(opts)
	-- 	vim.api.nvim_create_autocmd({ "BufAdd", "BufDelete" }, {
	-- 		callback = function()
	-- 			vim.schedule(function()
	-- 				pcall(nvim_bufferline)
	-- 			end)
	-- 		end,
	-- 	})
	-- end,
}
